### ISSUE TITLE
Remove empty magic methods

### ISSUE THREAD

**Issue by BenediktHensen** [rwth-acis/MixedRealityDart-Gruppe2#27]
In PrecisionMeasurement.cs, there are empty Start and Update methods. They have a performance impact since Unity has to perform a context change from an unmanaged environment to a managed environment and back.

Hence, delete the empty magic methods to save performance.

**Comment by danvonk** [comment]
Fixed by [https://github.com/rwth-acis/MixedRealityDart-Gruppe2/commit/1a0d8d5c199cc1c9af9bd7bf5e5000394e9e7136](url)
