### ISSUE TITLE
Change positioning from integers to floats

### ISSUE THREAD

**Issue by BenediktHensen** [rwth-acis/MixedRealityDart-Gruppe2#28]
The [random positioning of the target](https://github.com/rwth-acis/MixedRealityDart-Gruppe2/blob/b1465ed8c35f616334cdf1da7ad6bd310a466e3a/Assets/Scripts/GameManager.cs#L27) uses integers since you entered integers. Hence, the random function will only generate integer coordinates.
To get continuous placement options of the target, please change the integer values that are provided to Random.Range to floating point values.

**Comment by danvonk** [comment]
Fixed by c09d726cffa7066475e75bc3fd7f6b9ac69b8ceb
