### ISSUE TITLE
Simplify the GetComponent call and cache the spawner in the GameManager

### ISSUE THREAD

**Issue by BenediktHensen** [rwth-acis/MixedRealityDart-Gruppe2#29]
The call in line [21](https://github.com/rwth-acis/MixedRealityDart-Gruppe2/blob/b1465ed8c35f616334cdf1da7ad6bd310a466e3a/Assets/Scripts/GameManager.cs#L21) of the GameManager can be simplified using Generics:

`Spawner spawner = gameObject.GetComponent<Spawner>();`

Moreover, the GetComponent has an impact on performance if it is called regularly.
Hence, it would be better to cache the reference to the spawner once. You can accomplish this in two ways:
- Move the GetComponent call to an initialization function like Awake or Start that is only called once at the beginning. Store the fetched reference in a private variable that can be accessed in the SpawnTarget method.
- Create a field in the inspector and initialize it in the editor by dragging and dropping the spawner component onto it.

**Comment by danvonk** [comment]
Fixed by commit `d3c3c408a1122351fbfc638e8c1e94d138027195`
